wandb_version: 1

layer:
  desc: null
  value: 0
pos_start:
  desc: null
  value: 5
pos_end:
  desc: null
  value: 54
length:
  desc: null
  value: 49
alternating:
  desc: null
  value: "[ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1\n\
    \  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1\n  1]"
options:
  desc: null
  value: 2
rows:
  desc: null
  value: 8
cols:
  desc: null
  value: 8
max_epochs:
  desc: null
  value: 4
num_games_train:
  desc: null
  value: 30000
num_games_val:
  desc: null
  value: 10000
num_games_test:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0001
betas:
  desc: null
  value:
  - 0.9
  - 0.99
wd:
  desc: null
  value: 0.01
probe_name:
  desc: null
  value: flipped
wandb_project:
  desc: null
  value: Othello-GPT-Probes
get_state_stack_one_hot:
  desc: null
  value: __main__.get_state_stack_one_hot_flipped
modes:
  desc: null
  value: 1
relevant_mode:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717164584
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.17.0
      6: 4.41.1
      8:
      - 5
      13: linux-x86_64
